# HTTP Server
server:
#  port: 2222   # HTTP (Tomcat) port
  port: ${vcap.application.port:2222}

# Spring properties
spring:
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates

#---
#spring:
#  profiles: cloud