## Discovery Server Access
#eureka:
#  client:
#    serviceUrl:
##      defaultZone: http://localhost:1111/eureka/
#      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
#
#  instance:
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#    hostname: ${APPLICATION_DOMAIN}
#    nonSecurePort: 80
#
##By default
##spring.cloud.consul.host: localhost
##spring.cloud.consul.port: 8500