# Configure this Discovery Server
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
#    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

